// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtoLi9rjXXOoftkq49XbRW3fvQIX-380E',
    appId: '1:260552381914:web:0c34947601217e2d0e1ce3',
    messagingSenderId: '260552381914',
    projectId: 'zagel-chatapp-20dec',
    authDomain: 'zagel-chatapp-20dec.firebaseapp.com',
    storageBucket: 'zagel-chatapp-20dec.firebasestorage.app',
    measurementId: 'G-DQ0TD4498C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj0IffZf8p2OiKmEArqx4mLQwHmGd90x4',
    appId: '1:260552381914:android:7eeeedf46aa434500e1ce3',
    messagingSenderId: '260552381914',
    projectId: 'zagel-chatapp-20dec',
    storageBucket: 'zagel-chatapp-20dec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxiuNM555bcboqUHVaUTyMMh6DMopfHwE',
    appId: '1:260552381914:ios:9f4f2ef2c1c16bb20e1ce3',
    messagingSenderId: '260552381914',
    projectId: 'zagel-chatapp-20dec',
    storageBucket: 'zagel-chatapp-20dec.firebasestorage.app',
    iosBundleId: 'com.example.zagel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxiuNM555bcboqUHVaUTyMMh6DMopfHwE',
    appId: '1:260552381914:ios:9f4f2ef2c1c16bb20e1ce3',
    messagingSenderId: '260552381914',
    projectId: 'zagel-chatapp-20dec',
    storageBucket: 'zagel-chatapp-20dec.firebasestorage.app',
    iosBundleId: 'com.example.zagel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtoLi9rjXXOoftkq49XbRW3fvQIX-380E',
    appId: '1:260552381914:web:c67235a5da1dde700e1ce3',
    messagingSenderId: '260552381914',
    projectId: 'zagel-chatapp-20dec',
    authDomain: 'zagel-chatapp-20dec.firebaseapp.com',
    storageBucket: 'zagel-chatapp-20dec.firebasestorage.app',
    measurementId: 'G-XK435CGSG9',
  );
}
